[0-module][1-module-1-task] done
js-tasks-ru/jsbasic-20220310_kateshemenyok pull request #2
Opened 2022-03-15 09:47 UTC by CatherineShemenkova

2022-03-15 12:34 UTC, koalex requested changes
1-module-2-task не проходят тесты

2022-03-15 17:44 UTC, CatherineShemenkova commented
fixed

2022-03-17 03:20 UTC, koalex approved these changes

2022-03-17 03:38 UTC, koalex approved these changes

2022-03-17 03:39 UTC, merged